/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardPostsRouteImport } from './routes/dashboard.posts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/_layout/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/dashboard/posts',
  path: '/posts',
  getParentRoute: () => DashboardRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/about': typeof LayoutAboutRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/_layout' | '/about' | '/dashboard' | '/dashboard/posts' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dashboard' | '/dashboard/posts' | '/posts/$postId'
  id: '__root__' | '/' | '/_layout' | '/_layout/about' | '/dashboard' | '/dashboard/posts' | '/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
}
export interface DashboardRouteChildren {
  DashboardPostsRoute: typeof DashboardPostsRoute
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  DashboardRoute: typeof DashboardRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const layoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
}
const LayoutRouteWithChildren = LayoutRoute._addFileChildren(layoutRouteChildren)

const dashboardRouteChildren: DashboardRouteChildren = {
  DashboardPostsRoute: DashboardPostsRoute,
}
const DashboardRouteWithChildren = DashboardRoute._addFileChildren(dashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
