/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AboutLayoutRouteImport } from './routes/about/_layout'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as AboutLayoutIndexRouteImport } from './routes/about/_layout.index'
import { Route as DashboardPostsPostIdRouteImport } from './routes/dashboard/posts/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLayoutRoute = AboutLayoutRouteImport.update({
  id: '/about/_layout',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/dashboard/posts/',
  path: '/dashboard/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLayoutIndexRoute = AboutLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutLayoutRoute,
} as any).lazy(() =>
  import('./routes/about/_layout.index.lazy').then((d) => d.Route),
)
const DashboardPostsPostIdRoute = DashboardPostsPostIdRouteImport.update({
  id: '/dashboard/posts/$postId',
  path: '/dashboard/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/about/': typeof AboutLayoutIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/about': typeof AboutLayoutIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/_layout': typeof AboutLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/about/_layout/': typeof AboutLayoutIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard/'
    | '/dashboard/posts/$postId'
    | '/about/'
    | '/dashboard/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/posts/$postId'
    | '/about'
    | '/dashboard/posts'
  id:
    | '__root__'
    | '/'
    | '/about/_layout'
    | '/dashboard/'
    | '/dashboard/posts/$postId'
    | '/about/_layout/'
    | '/dashboard/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLayoutRoute: typeof AboutLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsPostIdRoute: typeof DashboardPostsPostIdRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/_layout': {
      id: '/about/_layout'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/_layout/': {
      id: '/about/_layout/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutLayoutIndexRouteImport
      parentRoute: typeof AboutLayoutRoute
    }
    '/dashboard/posts/$postId': {
      id: '/dashboard/posts/$postId'
      path: '/dashboard/posts/$postId'
      fullPath: '/dashboard/posts/$postId'
      preLoaderRoute: typeof DashboardPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutLayoutRouteChildren {
  AboutLayoutIndexRoute: typeof AboutLayoutIndexRoute
}

const AboutLayoutRouteChildren: AboutLayoutRouteChildren = {
  AboutLayoutIndexRoute: AboutLayoutIndexRoute,
}

const AboutLayoutRouteWithChildren = AboutLayoutRoute._addFileChildren(
  AboutLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLayoutRoute: AboutLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsPostIdRoute: DashboardPostsPostIdRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
