// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $index from "./routes/index.tsx";
import * as $api_items from "./routes/api/items.ts";
import * as $IslandCounter from "./islands/IslandCounter.tsx";
import * as $SignalsDemo from "./islands/SignalsDemo.tsx";
import * as $SharedSignalA from "./islands/SharedSignalA.tsx";
import * as $SharedSignalB from "./islands/SharedSignalB.tsx";
import * as $ServerDemo from "./islands/ServerDemo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/index.tsx": $index,
    "./routes/api/items.ts": $api_items,
  },
  islands: {
    "./islands/IslandCounter.tsx": $IslandCounter,
    "./islands/SignalsDemo.tsx": $SignalsDemo,
    "./islands/SharedSignalA.tsx": $SharedSignalA,
    "./islands/SharedSignalB.tsx": $SharedSignalB,
    "./islands/ServerDemo.tsx": $ServerDemo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
