// wasm-pkg/ is generated by wasm-pack from the Rust source.
// It contains: wasm_image.js (JS glue), wasm_image_bg.wasm (compiled binary), wasm_image.d.ts (types).
import init, {
  alloc,
  dealloc,
  double_values,
} from "./wasm-pkg/wasm_image.js";

// Module-level reference to Wasm linear memory.
// Captured after init() — before that the Wasm module is not loaded.
let memory: WebAssembly.Memory;

export class WasmNumberProcessor {
  async init(): Promise<void> {
    // init() fetches and instantiates the .wasm binary via WebAssembly.instantiateStreaming.
    // Returns the raw WebAssembly.Exports object, which includes the memory export.
    const exports = await init();
    memory = exports.memory;
  }

  // Full JS↔Wasm memory protocol for one operation:
  //   alloc → copy bytes in → call Rust → copy bytes out → free
  doubleArray(data: Int32Array): Int32Array {
    const ptr = this.copyIn(data);
    // Pass the byte offset (ptr) and element count. Rust reads count×4 bytes from ptr.
    double_values(ptr, data.length);
    const result = this.copyOut(ptr, data.byteLength);
    dealloc(ptr, data.byteLength);
    return result;
  }

  private copyIn(data: Int32Array): number {
    // Allocate in BYTES — each i32 is 4 bytes, so byteLength = length × 4.
    const ptr = alloc(data.byteLength);
    // Use a Uint8Array view for the raw byte copy.
    // ptr is always a byte offset; using a typed view directly would require dividing by element size.
    new Uint8Array(memory.buffer).set(new Uint8Array(data.buffer), ptr);
    return ptr;
  }

  private copyOut(ptr: number, byteLen: number): Int32Array {
    // slice() makes an independent copy of the bytes.
    // subarray() would give a view — dangerous because Wasm memory growth replaces
    // the underlying ArrayBuffer, leaving any existing view pointing at a detached buffer.
    const bytes = new Uint8Array(memory.buffer).slice(ptr, ptr + byteLen);
    return new Int32Array(bytes.buffer);
  }
}
